---
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "python"
        versions: ["3.12.*"]
    allow:
      - dependency-type: "all"
    open-pull-requests-limit: 3
