---
changelog:
  categories:
    - title: Breaking Changes 🧨
      labels:
        - major
        - breaking
    - title: New Features 🚀
      labels:
        - minor
        - enhancement
    - title: Other Changes 🏗️
      labels:
        - "*"
