# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        name: Trailing Whitespace Fixer
        description: "Removes trailing whitespace from lines"
        language: python
        types: [text]

      - id: end-of-file-fixer
        name: End of File Fixer
        description: "Ensures files end with a newline"
        language: python
        types: [text]

      - id: check-yaml
        name: YAML Syntax Checker
        description: "Checks the syntax of YAML files"
        language: python
        types: [yaml]

      - id: check-json
        name: JSON Syntax Checker
        description: "Checks the syntax of JSON files"
        language: python
        types: [json]

      - id: check-added-large-files
        name: Large File Checker
        description: "Prevents adding large files to the repository"
        language: python
        args: [--maxkb=500] # Set max file size to 500KB
        types: [file]

      - id: detect-aws-credentials
        name: AWS Credentials Detector
        description: "Scans for AWS credentials"
        language: python
        types: [text]
        exclude: ^tests/

      - id: detect-private-key
        name: Private Key Detector
        description: "Scans for private keys"
        language: python
        types: [text]
        exclude: ^tests/

  # Lint: Dockerfile
  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.0-beta
    hooks:
      - id: hadolint-docker
        entry: hadolint/hadolint:v2.12.1-beta hadolint

  # Lint: Dockerfile
  # We're linting .dockerfile files as well
  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.0-beta
    hooks:
      - id: hadolint-docker
        name: Lint *.dockerfile Dockerfiles
        entry: hadolint/hadolint:v2.12.1-beta hadolint
        types: [file]
        files: \.dockerfile$

  - repo: https://github.com/python-poetry/poetry
    rev: "1.8.0"
    hooks:
      - id: poetry-check
        name: Validate Poetry config
        description: Run poetry check to validate config
      - id: poetry-lock
        name: Update Poetry lock file
        description: Run poetry lock to update lock file
      - id: poetry-export
        name: Export lock file to requirements.txt
        description: Run poetry export to sync lock file with requirements.txt
      - id: poetry-install
        name: Install Poetry dependencies
        description: Run poetry install to install dependencies from the lock file

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.4.8
    hooks:
      # Run the linter.
      - id: ruff
        name: Ruff code check
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
        name: Ruff code format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        name: Run mypy for Python type-checking
        additional_dependencies:
          - pydantic
