[tool.poetry]
name = "boga-quotes"
version = "0.0.1"
description = "API to server random quotes from Kitboga."
authors = ["alex.candfield@gmail.com"]

[tool.ruff]
ignore = ["E203", "E266", "W503"]

[tool.mypy]
python_version = "3.12"
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
warn_unused_configs = true
check_untyped_defs = true
disallow_untyped_calls = true
disallow_untyped_defs = true
show_error_codes = true
plugins = ["pydantic.mypy"]

[tool.pydantic-mypy]
init_typed = true
warn_required_dynamic_aliases = true
